# Generated by Django 3.0.6 on 2020-07-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_auto_20200719_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='service',
        ),
        migrations.AddField(
            model_name='manager',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tickets.Services'),
        ),
    ]
