# Generated by Django 3.0.6 on 2020-07-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0006_auto_20200719_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='addresse',
        ),
    ]
