# Generated by Django 3.0.6 on 2020-07-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0007_remove_services_addresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='addresse',
            field=models.CharField(default='Yaoundé Cameroun , ENSP', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.Services'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.Services'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
